In [1]:
import pandas as pd

In [2]:
import pandas as pd

def cleansing(dataframes: list[pd.DataFrame]) -> pd.DataFrame:
    df = pd.concat(dataframes, ignore_index=True)
    missing_ratio = df.isna().sum() / len(df)
    df[df["Pos"] != "GK"]
    df = df.loc[:, missing_ratio < 0.3]

    # TODO: Clean Natio column

    # TODO: Map attributes to match names across datasets

    return df

# Previous to Kroos retirement

In [3]:
df_2022 = pd.read_csv("../data/players_data-2022_2023.csv")
df_2023 = pd.read_csv("../data/players_data-2023_2024.csv")

df_pre = cleansing([df_2022, df_2023])
df_pre

                 Player  Nation          Squad  Age
0      Brenden Aaronson     USA   Leeds United   22
1      Yunis Abdelhamid     MAR          Reims   35
2         Himad Abdelli     FRA         Angers   23
3     Salis Abdul Samed     GHA           Lens   22
4       Laurent Abergel     FRA        Lorient   30
...                 ...     ...            ...  ...
5642    Martin Ødegaard  no NOR        Arsenal   24
5643        Milan Đurić  ba BIH  Hellas Verona   33
5644             Player  Nation          Squad  Age
5645        Milan Đurić  ba BIH          Monza   33
5646   Mateusz Łęgowski  pl POL    Salernitana   20

[5647 rows x 4 columns]

# Posterior to Kroos retirement

In [4]:
df_2024 = pd.read_csv("../data/players_data-2024_2025.csv")
df_2025 = pd.read_csv("../data/players_data-2025_2026.csv")

df_post = cleansing([df_2024, df_2025])
df_post

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Pos_stats_misc,Comp_stats_misc,Age_stats_misc,Born_stats_misc,90s_stats_misc,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,OG
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24.0,2000.0,3,1,...,DF,eng Premier League,24.0,2000.0,1.0,0,0,0,0,0
1,2,Max Aarons,eng ENG,"DF,MF",Valencia,es La Liga,24.0,2000.0,4,1,...,"DF,MF",es La Liga,24.0,2000.0,1.3,2,0,0,0,0
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21.0,2003.0,1,1,...,DF,es La Liga,21.0,2003.0,0.7,1,0,0,2,0
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20.0,2004.0,6,0,...,"DF,MF",it Serie A,20.0,2004.0,1.0,1,0,0,4,0
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18.0,2006.0,1,0,...,FW,fr Ligue 1,18.0,2006.0,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5580,2727,Martín Zubimendi,es ESP,MF,Arsenal,eng Premier League,27.0,1999.0,31,30,...,MF,eng Premier League,27-066,1999.0,28.8,4,0,0,27,0
5581,2728,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,27.0,1998.0,20,13,...,MF,eng Premier League,27-113,1998.0,12.0,0,0,0,7,0
5582,2729,Luka Đurić,rs SRB,MF,Hoffenheim,de Bundesliga,22.0,2003.0,1,0,...,MF,de Bundesliga,22-295,2003.0,0.1,0,0,0,0,0
5583,2730,Milan Đurić,ba BIH,FW,Cremonese,it Serie A,35.0,1990.0,8,3,...,FW,it Serie A,35-322,1990.0,4.0,1,0,0,3,0
5584,2731,Milan Đurić,ba BIH,FW,Parma,it Serie A,35.0,1990.0,12,0,...,FW,it Serie A,35-322,1990.0,0.8,0,0,0,2,0